server:
  port: 8081

spring:
  datasource:
    password: docker
    username: docker
    url: jdbc:postgresql://localhost:5432/docker
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

jwt-consts:
  secret: pashasimplespring
  signature-algorithm: HS512
  access-expiration-date-in-ms: 3m
  refresh-expiration-date-in-ms: 2h

logic-status:
  logic-statuses:
    100: Запрос на изготовление отправлен
    200: Изготовлена
    300: Отправлена в отделение
    400: Находится в отделении банка
    430: Выдана клиенту
  default-message:
    Статус карты неизвестен